config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "welcome#index"
  get "/admin", to: "admin/base#home"

  namespace :admin do
    resources :products
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  has_many :articles
  has_many :supports
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :admin
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  has_many :articles
  belongs_to :parent, class_name: Category.name, optional: true
  has_many :children, class_name: Category.name, foreign_key: "parent_id"
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :buyer, class_name: User.name
  belongs_to :seller, class_name: User.name
  belongs_to :product_size
end

app/models/place_price.rb
# frozen_string_literal: true

class PlacePrice < ApplicationRecord
  belongs_to :user
  belongs_to :product_size
end

app/models/portfolio.rb
# frozen_string_literal: true

class Portfolio < ApplicationRecord
  belongs_to :user
  has_many :product_portfolios
  has_many :products, through: :product_portfolios
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_many :images, as: :imageable
  has_many :product_sizes
  has_many :product_portfolios
  has_many :portfolios, through: :product_portfolios
  has_one_attached :image

  PRODUCT_PARAMS = [:name, :style, :retail_price, :color_way, :description, :release_date, :category_id, :image].freeze

  validates :name, presence: true, length: {maximum: Settings.max_text_length}
  validates :retail_price, presence: true, numericality: {only_float: true}
  validates :style, presence: true, length: {maximum: Settings.max_text_length}
  validates :color_way, presence: true, length: {maximum: Settings.max_text_length}
  validate :release_date_cannot_be_in_the_future

  scope :by_lastest, ->{order created_at: :desc}

  def release_date_cannot_be_in_the_future
    errors.add(:release_date, t(".not_in_future")) if release_date.present? && release_date > Time.zone.today
  end
end

app/models/product_portfolio.rb
# frozen_string_literal: true

class ProductPortfolio < ApplicationRecord
  belongs_to :product
  belongs_to :portfolio
end

app/models/product_size.rb
# frozen_string_literal: true

class ProductSize < ApplicationRecord
  belongs_to :product
  belongs_to :size
  has_many :place_prices
  has_one :order
end

app/models/size.rb
# frozen_string_literal: true

class Size < ApplicationRecord
  has_many :product_sizes
end

app/models/support.rb
# frozen_string_literal: true

class Support < ApplicationRecord
  belongs_to :admin
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :addresses
  has_many :place_prices
  has_many :portfolios
  has_many :orders, foreign_key: :buyer_id
  has_many :sells, foreign_key: :seller_id, class_name: Order.name
end

app/controllers/admin/bases_controller.rb
# frozen_string_literal: true

class Admin::BasesController < ApplicationController
  def home; end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

class Admin::ProductsController < Admin::BasesController
  before_action :load_category, only: %i(new create)

  def index
    @products = Product.by_lastest.page(params[:page]).per Settings.per_page
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    if @product.save
      flash[:success] = t ".create_success"
      redirect_to admin_products_path
    else
      flash[:error] = t ".create_unsuccess"
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit Product::PRODUCT_PARAMS
  end

  def load_category
    @category = Category.all
    return if @category

    flash[:error] = t ".not_found_category"
    redirect_to admin_products_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def create_index params_page, index, per_page
    params_page = 1 if params_page.nil?
    (params_page.to_i - 1) * per_page.to_i + index.to_i + 1
  end
end

app/views/admin/products/index.html.erb
<% provide(:title, t(".products")) %>
<div class="row">
  <div class="col-lg-12">
    <!-- search -->
    <%= link_to t(".create_new_product"), new_admin_product_path, class: "btn btn-success" %>
    <table width="100%" class="table table-bordered table-hover" id="datatable">
      <thead>
        <tr>
          <th><%= t ".stt" %></th>
          <th><%= t ".products" %></th>
          <th><%= t ".description" %></th>
          <th><%= t ".image" %></th>
          <th><%= t ".style" %></th>
          <th><%= t ".retail_price" %></th>
          <th><%= t ".color_way" %></th>
          <th><%= t ".release_date" %></th>
          <th colspan="2"><%= t ".action" %></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |product, index| %>
        <tr>
          <td><%= create_index params[:page], index, Settings.per_page %></td>
          <td><%= product.name %></td>
          <td>
            <%= product.description %>
          </td>
          <td><%= image_tag product.image if product.image.attached? %></td>
          <td><%= product.style %></td>
          <td><%= product.retail_price %></td>
          <td><%= product.color_way %></td>
          <td><%= product.release_date %></td>
          <td>
            <%= link_to t(".edit"), "#TODO-edit", class: "btn btn-warning" %>
          </td>
          <td>
            <%= link_to t(".delete"), "#TODO-delete", class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @products %>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, t(".add_new_product")) %>
<% provide(:button_text, t(".create_product")) %>
<h1><%= t ".add_new_product" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_area :name, placeholder: t(".name") %>

      <%= f.label :style %>
      <%= f.text_area :style, placeholder: t(".style") %>

      <%= f.label :color_way %>
      <%= f.text_area :color_way, placeholder: t(".color_way") %>

      <%= f.label :retail_price %>
      <%= f.text_area :retail_price, placeholder: t(".retail_price") %>

      <%= f.label :description %>
      <%= f.text_area :description, placeholder: t(".description") %>

      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

      <%= f.label :release_date %>
      <%= f.date_select :release_date, :order => [:month, :day, :year] %>

      <%= f.select :category_id do %>
        <% @category.each do |c| -%>
          <%= content_tag :option, c.name, value: c.id %>
        <% end %>
      <% end %>
      
      <%= f.submit t(".create_product"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer primary-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".recent_updates" %></h4>
          <ul>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Google+</a></li>
            <li><a href="#">Linkedin</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".popular_releases" %></h4>
        </div>
      </div>
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".air_jordan" %></h4>
        </div>
      </div>
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".adidas" %></h4>
        </div>
      </div>
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".nike" %></h4>
        </div>
      </div>
      <div class="col-md-2 col-sm-2">
        <div class="widget clearfix">
          <h4 class="widget-title"><%= t ".streetwear" %></h4>
        </div>
      </div>
    </div>
  </div>
</footer>
<footer class="footer secondary-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
        <p><%= t ".copyright" %></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header site-header affix">
    <div class="container">
      <nav class="navbar navbar-default yamm">
        <div class="container-fluid">
          <div id="navbar" class="navbar-collapse collapse">
            <%= image_tag("logo.png", alt:"StockX")%>
            <ul class="nav navbar-right">
              <li><%= link_to t("layouts.header.browse"), "#TODO-browse", class:"menu-header" %></li>
              <li><%= link_to t(".news"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".app"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".portfolio"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".about"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".faq"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".login"), "#TODO", class:"menu-header" %></li>
              <li><%= link_to t(".sign_up"), "#TODO", class:"menu-header" %></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hypebid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container-padding">
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %><%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Heroku!</h1>